version: 2.1
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Angular Build
          command: |
            npm run build
  deploy:
    docker:
      - image: ubuntu:18.04
    steps:
      - add_ssh_keys:
        fingerprints:
          - "89:72:06:ee:03:0c:35:72:62:22:03:d7:11:5e:1f:0e"
      - run:
          name: SCP Files
          command: |
            scp dist/ui/* ec2-user@prestonmontewest.com:/var/www/prestonmontewest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
        filters:
          branches:
            only: dev
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: dev
